### ISSUE TITLE
Sort button is green

### ISSUE THREAD

**Issue by jakobdylanc** [shirsig/Cleanup#12] opened 2019-08-30 13:15 UTC
I'm using this addon with Bagnon and the sort button's texture appears to be broken. It's showing as solid green.

**Comment by shirsig** [comment] 2019-08-30 16:49
I know but this is bagnon's sort button. The problem is bagnon thinks this is the retail bagsort and tries to show its own sort button but the texture doesn't exist in the 1.13 client.
Anyway, this should be fixed in bagnon (either they should only show the button in retail or they should include the texture)

**Closed as completed by shirsig** 2019-08-30 16:49 UTC
